### ISSUE TITLE
traefik/020-depoyment - wrong acme.json location in default setup

### ISSUE THREAD

**Issue by letsbuildfoze** [imixs/imixs-cloud#34]
Hello,
I got a error when i use the kubect apply -f 020 deployments traefik.
When i want to use acme certificate, i create the folder /var/lib/traefik ans the file acme.json with chmod 600 permissions.
I already create the folders in all of my nodes.
But i got the error "unable to find the files or fonder /var/lib/traefik. Switch to default"

What do you think?

**Comment by rsoika** [comment]
How did you configure your volume mapping to provide the acme.json file?

[here](https://github.com/imixs/imixs-cloud/blob/master/management/traefik/README.md) you can read about how to setup the file with longhorn volumes. 
Creating the file on each node without using longhonr should also be ok but how did your configuration look like?

**Comment by letsbuildfoze** [comment]
The error:
time="2020-06-05T10:57:28Z" level=info msg="Configuration loaded from flags."
time="2020-06-05T10:57:28Z" level=info msg="Traefik version 2.2.1 built on 2020-04-29T18:02:09Z"
time="2020-06-05T10:57:28Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/contributing/data-collection/\n"
time="2020-06-05T10:57:28Z" level=error msg="The ACME resolver \"default\" is skipped from the resolvers list because: unable to get ACME account: open /var/lib/traefik/acme.json: no such file or directory"
time="2020-06-05T10:57:28Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2020-06-05T10:57:28Z" level=info msg="Starting provider *traefik.Provider {}"
time="2020-06-05T10:57:28Z" level=info msg="Starting provider *ingress.Provider {}"
time="2020-06-05T10:57:28Z" level=info msg="ingress label selector is: \"\"" providerName=kubernetes
time="2020-06-05T10:57:28Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetes
time="2020-06-05T10:57:28Z" level=info msg="Starting provider *crd.Provider {}"
time="2020-06-05T10:57:28Z" level=info msg="label selector is: \"\"" providerName=kubernetescrd
time="2020-06-05T10:57:28Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetescrd
time="2020-06-05T10:57:30Z" level=error msg="middleware \"default-https-redirect@kubernetescrd\" does not exist" entryPointName=web routerName=default-traefik-dashboard-272dc56f9fbc5761ef41@kubernetescrd
time="2020-06-05T10:57:30Z" level=error msg="middleware \"default-https-redirect@kubernetescrd\" does not exist" routerName=websecure-default-traefik-dashboard-272dc56f9fbc5761ef41@kubernetescrd entryPointName=websecure
time="2020-06-05T10:57:30Z" level=error msg="the router websecure-default-traefik-dashboard-272dc56f9fbc5761ef41@kubernetescrd uses a non-existent resolver: default"

The file:

###############################
# ServiceAccount
###############################
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: kube-system

###############################
# Deployment
###############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: traefik
    release: traefik
  name: traefik
  namespace: kube-system

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
      release: traefik
  template:
    metadata:
      labels:
        app: traefik
        release: traefik
    spec:
      containers:
      - args:
        - --api
        - --api.insecure=true
        # Set insecure to fals to enable basic auth
        #- --api.insecure=false
        - --api.dashboard=true
        - --accesslog
        - --global.checknewversion=true
        - --entryPoints.traefik.address=:8100
        - --entryPoints.web.address=:80
        - --entryPoints.websecure.address=:443

        # permanent redirecting of all requests on http (80) to https (443)
        - --entrypoints.web.http.redirections.entryPoint.to=websecure
        - --entrypoints.websecure.http.tls.certResolver=default

        # Let's Encrypt Configurtion:
        # Please note that this is the staging Let's Encrypt server configuration.
        # Once you get things working, you should remove that following line.
        - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
        - --certificatesresolvers.default.acme.email=f.pheron@foze.fr
        - --certificatesresolvers.default.acme.storage=/var/lib/traefik/acme.json
        - --certificatesresolvers.default.acme.tlschallenge=true
 - --ping=true
        - --providers.kubernetescrd=true
        - --providers.kubernetesingress=true

        # Use log level= INFO or DEBUG
        - --log.level=INFO
        image: traefik:2.2.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik
        ports:
        - containerPort: 8100
          name: admin
          protocol: TCP
        - containerPort: 80
          name: web
          protocol: TCP
        - containerPort: 443
          name: websecure
          protocol: TCP

        # optional storage
  # enable this option only in case you have defined a persistence volume claim
        #volumeMounts:
        #- name: traefik-data
        #  mountPath: /var/lib/traefik

        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: traefik
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60

      # optional storage
      # enable this option only in case you have defined a persistence volume claim
      #volumes:
      #  - name: traefik-data
      #    persistentVolumeClaim:
      #      claimName: traefik-data
###############################
# Service
###############################
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik
    release: traefik
  name: traefik
  namespace: kube-system
spec:
  externalIPs:
  - 91.121.31.181
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: 443
  - name: admin
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: traefik
    release: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}






#########################################################
# The Middleware configuration contains middleware componenst
# for a HTTP->HTTS redirection and a BasicAuth example.
#########################################################
###############################
# Middleware for basicAuth
###############################
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
spec:
  basicAuth:
    secret: authsecret

---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: default

#------------ Paste your own password file content here --------------
data:
  users: |2
    YWRtaW46JGFwcjEkWXdmLkF6Um0kc3owTkpQMi55cy56V2svek43aENtLwoKdXNl
    cjokYXByMSRaU2VKQW1pOSRVV1AvcDdsQy9KSzdrbXBIMXdGL28uCgo=
###############################
# Middleware for HTTP->HTTPS
# This middleware is not needed in case of:
#      entrypoints.web.http.redirections.entryPoint.to=websecure
###############################
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: https-redirect
#spec:
#  redirectScheme:
#    scheme: https
#    permanent: true
#    #port: 443


###############################
# Middleware for CORS
###############################
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-all
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "POST"
    accessControlAllowOriginList:
      - "origin-list-or-null"
    accessControlMaxAge: 100
    accessControlAllowHeaders:
      - "Content-Type"
    addVaryHeader: true

**Comment by letsbuildfoze** [comment]
The error:
time="2020-06-05T10:57:28Z" level=info msg="Configuration loaded from flags."
time="2020-06-05T10:57:28Z" level=info msg="Traefik version 2.2.1 built on 2020-04-29T18:02:09Z"
time="2020-06-05T10:57:28Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/contributing/data-collection/\n"
time="2020-06-05T10:57:28Z" level=error msg="The ACME resolver \"default\" is skipped from the resolvers list because: unable to get ACME account: open /var/lib/traefik/acme.json: no such file or directory"
time="2020-06-05T10:57:28Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2020-06-05T10:57:28Z" level=info msg="Starting provider *traefik.Provider {}"
time="2020-06-05T10:57:28Z" level=info msg="Starting provider *ingress.Provider {}"
time="2020-06-05T10:57:28Z" level=info msg="ingress label selector is: \"\"" providerName=kubernetes
time="2020-06-05T10:57:28Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetes
time="2020-06-05T10:57:28Z" level=info msg="Starting provider *crd.Provider {}"
time="2020-06-05T10:57:28Z" level=info msg="label selector is: \"\"" providerName=kubernetescrd
time="2020-06-05T10:57:28Z" level=info msg="Creating in-cluster Provider client" providerName=kubernetescrd
time="2020-06-05T10:57:30Z" level=error msg="middleware \"default-https-redirect@kubernetescrd\" does not exist" entryPointName=web routerName=default-traefik-dashboard-272dc56f9fbc5761ef41@kubernetescrd
time="2020-06-05T10:57:30Z" level=error msg="middleware \"default-https-redirect@kubernetescrd\" does not exist" routerName=websecure-default-traefik-dashboard-272dc56f9fbc5761ef41@kubernetescrd entryPointName=websecure

**Comment by letsbuildfoze** [comment]
Here the file:

`###############################
# ServiceAccount
###############################
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik
  namespace: kube-system

###############################
# Deployment
###############################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: traefik
    release: traefik
  name: traefik
  namespace: kube-system

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
      release: traefik
  template:
    metadata:
      labels:
        app: traefik
        release: traefik
    spec:
      containers:
      - args:
        - --api
        - --api.insecure=true
        # Set insecure to fals to enable basic auth
        #- --api.insecure=false
        - --api.dashboard=true
        - --accesslog
        - --global.checknewversion=true
        - --entryPoints.traefik.address=:8100
        - --entryPoints.web.address=:80
        - --entryPoints.websecure.address=:443

        # permanent redirecting of all requests on http (80) to https (443)
        - --entrypoints.web.http.redirections.entryPoint.to=websecure
        - --entrypoints.websecure.http.tls.certResolver=default

        # Let's Encrypt Configurtion:
        # Please note that this is the staging Let's Encrypt server configuration.
        # Once you get things working, you should remove that following line.
        - --certificatesresolvers.default.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
        - --certificatesresolvers.default.acme.email=f.phxxx@foxx.fr
        - --certificatesresolvers.default.acme.storage=/var/lib/traefik/acme.json
        - --certificatesresolvers.default.acme.tlschallenge=true

        - --ping=true
        - --providers.kubernetescrd=true
        - --providers.kubernetesingress=true

        # Use log level= INFO or DEBUG
        - --log.level=INFO
        image: traefik:2.2.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ping
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        name: traefik
        ports:
        - containerPort: 8100
          name: admin
          protocol: TCP
        - containerPort: 80
          name: web
          protocol: TCP
        - containerPort: 443
          name: websecure
          protocol: TCP

        # optional storage 
        # enable this option only in case you have defined a persistence volume claim
        #volumeMounts:
        #- name: traefik-data
        #  mountPath: /var/lib/traefik

        readinessProbe:
          failureThreshold: 1
          httpGet:
            path: /ping
            port: 8100
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: traefik
      serviceAccountName: traefik
      terminationGracePeriodSeconds: 60
      
      # optional storage
      # enable this option only in case you have defined a persistence volume claim
      #volumes:
      #  - name: traefik-data
      #    persistentVolumeClaim:
      #      claimName: traefik-data



###############################
# Service
###############################
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: traefik
    release: traefik
  name: traefik
  namespace: kube-system
spec:
  externalIPs:
  - 91.xx.xx.xx
  externalTrafficPolicy: Cluster
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  - name: websecure
    port: 443
    protocol: TCP
    targetPort: 443
  - name: admin
    port: 8100
    protocol: TCP
    targetPort: 8100
  selector:
    app: traefik
    release: traefik
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}






#########################################################
# The Middleware configuration contains middleware componenst
# for a HTTP->HTTS redirection and a BasicAuth example. 
#########################################################



###############################
# Middleware for basicAuth 
###############################
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: basic-auth
spec:
  basicAuth:
    secret: authsecret

---
apiVersion: v1
kind: Secret
metadata:
  name: authsecret
  namespace: default

#------------ Paste your own password file content here --------------
data:
  users: |2
    YWRtaW46JGFwcjEkWXdmLkF6Um0kc3owTkpQMi55cy56V2svek43aENtLwoKdXNl
    cjokYXByMSRaU2VKQW1pOSRVV1AvcDdsQy9KSzdrbXBIMXdGL28uCgo=


###############################
# Middleware for HTTP->HTTPS
# This middleware is not needed in case of: 
#      entrypoints.web.http.redirections.entryPoint.to=websecure
###############################
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: https-redirect
#spec:
#  redirectScheme:
#    scheme: https
#    permanent: true
#    #port: 443


###############################
# Middleware for CORS
###############################
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-all
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
      - "POST"
    accessControlAllowOriginList: 
      - "origin-list-or-null"
    accessControlMaxAge: 100
    accessControlAllowHeaders:
      - "Content-Type"
    addVaryHeader: true



`

**Comment by letsbuildfoze** [comment]
[020-deployment.zip](https://github.com/imixs/imixs-cloud/files/4735665/020-deployment.zip)

Here the file

**Comment by rsoika** [comment]
Ok, I think I understand the problem. 
Try to change the following traefik argument in your 020-deplyoment.yaml file:

    - --certificatesresolvers.default.acme.storage=acme.json
       

The file is part of the POD/Container so you do not have to provide any external file on the host nodes.

The configuration 

     - --certificatesresolvers.default.acme.storage=/var/lib/traefik/acme.json
       
is only necessary in conjunction with a persistence volume which you do not use.

I am pretty sure this will solve your problem. Please let me know if it works. Because we need to fix the default setup...

**Comment by letsbuildfoze** [comment]
Thanks, for your help.

I got a another error:

**Comment by rsoika** [comment]
ok - in general my advice is to stay cool because things need there time and traefik logs a lot of messages during startup even if all is fine. But anyway you can do the following tests.

ssh into the pod your trafik is running (you can use k9s ) or with kubectl

    $ kubectl exec traefik-797d56bc7d-hvfr5 -it -n kube-system -- /bin/sh

you can get the pod name with   `$ kubectl get pods -n kube-system`

next try a ping from inside the pod:

     $ ping acme-staging-v02.api.letsencrypt.org

so you will see if internet connection out from the pod is ok (it should be).

The other test is looking into your acme.yaml file from within the POD

    $ cat /var/lib/traefik/acme.json

(I am not sure if the location of the file in you case it correct. It may be that the acme.json file is located in the root   `$ cat /acme.json`

What you should see in this file are the collected lets-encrypt certificates. For example things like

     .....
    "Store": "default"
      },
      {
        "domain": {
          "main": "panel-traefik.xxx.fr"
        },
        "certificate": "LS0tLS1......
       .......


And a very important point is that your domain is not yet known by all dns servers - also lets encrypt need to know your address. Especially if you change the IP address it can take up to 24 hours until your domain is reachable again. And lets encrypt will only be able to generate a certificate if the domain is known.

I hope this helps.

Btw: independent from the lets'encrypt stuff - you should be able to access your domain in any case - even if your browser states that the connection is not trustable. I hope this is working? 
In the first place your ingress must work - than you can look into the certificate stuff....

**Comment by letsbuildfoze** [comment]
Thanks fo your help!
I close the issue

**Comment by rsoika** [comment]
How have you configured the acme.json location now?
