### ISSUE TITLE
TLS with custom certificates

### ISSUE THREAD

**Issue by sonisaurabh19** [imixs/imixs-cloud#42]
Hi, thanks for this great repo! Can you please provide an example of using custom certificates in place of acme. I have a certfile and keyfile that have worked well for me in setting up TLS for traefik and all services it is routing to in Docker.

**Comment by rsoika** [comment]
If you have your own certificate you do not need the acme setup for Let's Encrypt. acme is a protocol for automating interactions between your server and a certificate authority to generate and verify certificates like Let's Encrypt . 

So you should ignore/remove the acme settings in the 020-deplomyent.yaml file and replace them with the traefik TLS configuration. Find details [here](https://docs.traefik.io/https/tls/). 

You need something like this:

```
- --tls.certificates.certFile=/path/to/domain.cert
- --tls.certificates.keyFile: /path/to/domain.key
```

But I can't provide you with a full example as I did not have done this before by myself. 

But please share your outcome here so we can extend the documentation later for other users.
