### ISSUE TITLE
How to create basic auth secret?

### ISSUE THREAD

**Issue by sonisaurabh19** [imixs/imixs-cloud#43]
Hi, the middleware for basic-auth that uses the authsecret has user "admin" and password "adminadmin". Can you please share steps on how you generated the following data:
```
  #------------ Paste your own password file content here (default user/password=admin/adminadmin)--------------
  data:
    users: |2
      YWRtaW46JGFwcjEkWXdmLkF6Um0kc3owTkpQMi55cy56V2svek43aENtLwoKdXNl
      cjokYXByMSRaU2VKQW1pOSRVV1AvcDdsQy9KSzdrbXBIMXdGL28uCgo=
```

**Comment by rsoika** [comment]
You can use the commadline tool 'htpasswd' which is part of the apache2-utils. The content of that file can than be copy/paste into the middleware configuration. See [here](https://github.com/imixs/imixs-cloud/blob/master/doc/INGRESS.md#1-generate-a-password-file)

Let me know if this answers your question.

**Comment by sonisaurabh19** [comment]
thanks @rsoika that helps, although one followup - what does `users: |2` mean? Like 2 users? And if there are 2 users, why don't we specify both passwords like:
```
users: |2
   ABC......
   DEF.......
```

**Comment by rsoika** [comment]
I feared this question ;-)
I don't really know what the `|2` means and how exactly this kind of configuration should be structured in a Kubernetes object description....
