### ISSUE TITLE
Best practice for disks with longhorn 

### ISSUE THREAD

**Issue by guidtz** [imixs/imixs-cloud#52]
Hello, my question is about disks with longhorn. On all nodes I have a second disk /dev/vdb. How to use them with longhorn ? 
Thanks for you're work

**Comment by rsoika** [comment]
That's quite easy. If you go into the Longhorn Web UI you can edit your nodes and add multiple disks:
![image](https://user-images.githubusercontent.com/1339124/99636435-b56e1d00-2a43-11eb-8450-1dd76649159f.png)

Before editing you have to disable the node.

Let me know if this works for you.

**Comment by guidtz** [comment]
Ok I'll go to try this soon. I thought it had to be done on deployment.

**Comment by guidtz** [comment]
Test in Progress
![Uploading longhorn-ui-add-disk.png…]()
