### ISSUE TITLE
Ceph : Error EINVAL: Failed to connect to ceph01 (ceph01)

### ISSUE THREAD

**Issue by guidtz** [imixs/imixs-cloud#53]
Hello,

  do you have any problem to connect node to ceph master ? When I tried to add a node : 

```
$ sudo ceph orch host add ceph01
Error EINVAL: Failed to connect to ceph01 (ceph01).
Check that the host is reachable and accepts connections using the cephadm SSH key

you may want to run:
> ceph cephadm get-ssh-config > ssh_config
> ceph config-key get mgr/cephadm/ssh_identity_key > key
> ssh -F ssh_config -i key root@ceph01
```

So I configured ssh access to node ceph01 with .ssh/config and It's works manually : 
```
$ sudo ssh ceph01
Warning: Permanently added 'ceph01,192.168.85.31' (ECDSA) to the list of known hosts.
Linux ceph01 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Sat Nov 21 18:48:29 2020 from 192.168.85.30
root@ceph01:~#
```

Do you have an idea ?

**Comment by rsoika** [comment]
Yes I could be that you node is not accepting the public key from the root node.
Take a look at [this tutorial](https://ralph.blog.imixs.com/2020/04/14/ceph-octopus-running-on-debian-buster/). Here I explained the procedure in more detail in the section "Expending the Cluster". 

Let me know if you can solve your issue so that we can improve the documentation.

**Comment by vitalyUstalu** [comment]
Hello,
I had the same problem with a manualy installed ceph cluster (via cephadm) and fixed it by installing python3 on target host.
I found it here https://github.com/ceph/ceph/blob/master/src/pybind/mgr/cephadm/module.py#L1008 Unfortunately this message is not displayed further.

**Comment by guidtz** [comment]
Ok I'll go to test this soon.

**Comment by thatsk** [comment]
single node cluster is not working also for quincy release hope fully better docs make better product

**Comment by rsoika** [comment]
@thatsk Which exact problem do you have? Do you have problems to install your ceph cluster? I have written a new tutorial how to install Ceph on Debian: https://ralph.blog.imixs.com/2021/10/03/ceph-pacific-running-on-debian-11-bullseye/

As I recommand you should run ceph independent from your Kubernetes cluster. So if it is a ceph problem you need to search first for help in the [ceph community](https://ceph.com/en/community/). 

If your ceph cluster is up and running, but your imixs-cloud setup does not be able to create a static persistence volume connected to your Ceph than we can discuss it here.
