### ISSUE TITLE
Replace Traefik with Nginx

### ISSUE THREAD

**Issue by rsoika** [imixs/imixs-cloud#60]
Nginx is the most popular  Ingress Controller maintained by the K8s team, built on top of NGINX reverse proxy. It is a popular option for simple HTTP/S routing and SSL termination use case. Hence of the popularity, there is comprehensive documentation and tutorials available for common ingress tasks and related tools.

We replace traefik with nginx because of the high configuration complexity of traefik. 

If you need a straightforward simple reverse proxy, ingress-nginx is a safe and decisive option. On the other hand, if you are looking for high performance and also additional features supported by NGINX, consider using the Ingress Controller from NGINX instead.

https://github.com/kubernetes/ingress-nginx

**Comment by ankanheesun** [comment]
HI @rsoika 

Is it still possible to have Traefik running inside Kubernetes? I tried with your guide at imixs-cloud/management/traefik but I was not successful... 

Of course, if there is no way to configure Traefik with K8S, I will continue following your guide to configure Nginx Ingress. However, I prefer to learn how to integrate Traefik !!!

Thank you in advanced !!!

**Comment by rsoika** [comment]
Yes, it is possible to run Traefik instead of the Nginx Controller in K8S. 
The problem was that Traefik is not so easy to setup, as it was in the early beginning. And with the latest API changes in Kubernetes 1.20 my old guide did (again) no longer work.
I was a little bit frustrated than, because I invested many hours to write the old guide. So finally I decided to give the Nginx Controller a chance. And my personal conclusion was, that it is much more easy to configure Nginx instead of Traefik. This is why I replaced Traefik with Nginx in Imixs-Cloud. The Nginx controller is supported directly by the Kubernetes community and has no disadvantage.

So, I am sorry that I can't help you with the latest version of Traefik. But if you like traefik, give it a try. The developers from the traefik team are very helpful and will support you. And if you succeeded than maybe we can update the old guide and add it as an valid alternative to Nginx Guide.....

**Comment by ankanheesun** [comment]
Thank you for your detailed explanations... They're useful with my choice. Yes, I will try with Traefik and come back to you if I was successful. Of course, I agree with you that Nginx has no disadvantages and also supported directly by K8s. So it would be a good choice for us. I will try it also. 

Thank again for your feed back !!!
